/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace ChildVitaGrant {
  export type GrantStruct = {
    id: PromiseOrValue<BigNumberish>;
    caregiver: PromiseOrValue<string>;
    childId: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
    attendanceVerified: PromiseOrValue<boolean>;
    paid: PromiseOrValue<boolean>;
    zkProofHash: PromiseOrValue<string>;
    timestamp: PromiseOrValue<BigNumberish>;
  };

  export type GrantStructOutput = [
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    boolean,
    boolean,
    string,
    BigNumber
  ] & {
    id: BigNumber;
    caregiver: string;
    childId: BigNumber;
    amount: BigNumber;
    attendanceVerified: boolean;
    paid: boolean;
    zkProofHash: string;
    timestamp: BigNumber;
  };
}

export interface ChildVitaGrantInterface extends utils.Interface {
  functions: {
    "authorizedVerifiers(address)": FunctionFragment;
    "createGrant(address,uint256,uint256)": FunctionFragment;
    "getGrant(uint256)": FunctionFragment;
    "grantCount()": FunctionFragment;
    "grants(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "releaseGrant(uint256)": FunctionFragment;
    "verifyAttendance(uint256,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "authorizedVerifiers"
      | "createGrant"
      | "getGrant"
      | "grantCount"
      | "grants"
      | "owner"
      | "releaseGrant"
      | "verifyAttendance"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "authorizedVerifiers",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "createGrant",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getGrant",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "grantCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grants",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releaseGrant",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAttendance",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGrant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grants", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAttendance",
    data: BytesLike
  ): Result;

  events: {
    "AttendanceVerified(uint256,string)": EventFragment;
    "GrantCreated(uint256,address,uint256)": EventFragment;
    "GrantPaid(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AttendanceVerified"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GrantCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GrantPaid"): EventFragment;
}

export interface AttendanceVerifiedEventObject {
  id: BigNumber;
  zkProofHash: string;
}
export type AttendanceVerifiedEvent = TypedEvent<
  [BigNumber, string],
  AttendanceVerifiedEventObject
>;

export type AttendanceVerifiedEventFilter =
  TypedEventFilter<AttendanceVerifiedEvent>;

export interface GrantCreatedEventObject {
  id: BigNumber;
  caregiver: string;
  amount: BigNumber;
}
export type GrantCreatedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  GrantCreatedEventObject
>;

export type GrantCreatedEventFilter = TypedEventFilter<GrantCreatedEvent>;

export interface GrantPaidEventObject {
  id: BigNumber;
}
export type GrantPaidEvent = TypedEvent<[BigNumber], GrantPaidEventObject>;

export type GrantPaidEventFilter = TypedEventFilter<GrantPaidEvent>;

export interface ChildVitaGrant extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ChildVitaGrantInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    authorizedVerifiers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    createGrant(
      _caregiver: PromiseOrValue<string>,
      _childId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getGrant(
      _grantId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[ChildVitaGrant.GrantStructOutput]>;

    grantCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    grants(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        boolean,
        boolean,
        string,
        BigNumber
      ] & {
        id: BigNumber;
        caregiver: string;
        childId: BigNumber;
        amount: BigNumber;
        attendanceVerified: boolean;
        paid: boolean;
        zkProofHash: string;
        timestamp: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    releaseGrant(
      _grantId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verifyAttendance(
      _grantId: PromiseOrValue<BigNumberish>,
      _zkProofHash: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  authorizedVerifiers(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  createGrant(
    _caregiver: PromiseOrValue<string>,
    _childId: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getGrant(
    _grantId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ChildVitaGrant.GrantStructOutput>;

  grantCount(overrides?: CallOverrides): Promise<BigNumber>;

  grants(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      boolean,
      boolean,
      string,
      BigNumber
    ] & {
      id: BigNumber;
      caregiver: string;
      childId: BigNumber;
      amount: BigNumber;
      attendanceVerified: boolean;
      paid: boolean;
      zkProofHash: string;
      timestamp: BigNumber;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  releaseGrant(
    _grantId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verifyAttendance(
    _grantId: PromiseOrValue<BigNumberish>,
    _zkProofHash: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    authorizedVerifiers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    createGrant(
      _caregiver: PromiseOrValue<string>,
      _childId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getGrant(
      _grantId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ChildVitaGrant.GrantStructOutput>;

    grantCount(overrides?: CallOverrides): Promise<BigNumber>;

    grants(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        boolean,
        boolean,
        string,
        BigNumber
      ] & {
        id: BigNumber;
        caregiver: string;
        childId: BigNumber;
        amount: BigNumber;
        attendanceVerified: boolean;
        paid: boolean;
        zkProofHash: string;
        timestamp: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    releaseGrant(
      _grantId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    verifyAttendance(
      _grantId: PromiseOrValue<BigNumberish>,
      _zkProofHash: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AttendanceVerified(uint256,string)"(
      id?: null,
      zkProofHash?: null
    ): AttendanceVerifiedEventFilter;
    AttendanceVerified(
      id?: null,
      zkProofHash?: null
    ): AttendanceVerifiedEventFilter;

    "GrantCreated(uint256,address,uint256)"(
      id?: null,
      caregiver?: null,
      amount?: null
    ): GrantCreatedEventFilter;
    GrantCreated(
      id?: null,
      caregiver?: null,
      amount?: null
    ): GrantCreatedEventFilter;

    "GrantPaid(uint256)"(id?: null): GrantPaidEventFilter;
    GrantPaid(id?: null): GrantPaidEventFilter;
  };

  estimateGas: {
    authorizedVerifiers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createGrant(
      _caregiver: PromiseOrValue<string>,
      _childId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getGrant(
      _grantId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantCount(overrides?: CallOverrides): Promise<BigNumber>;

    grants(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    releaseGrant(
      _grantId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verifyAttendance(
      _grantId: PromiseOrValue<BigNumberish>,
      _zkProofHash: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    authorizedVerifiers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createGrant(
      _caregiver: PromiseOrValue<string>,
      _childId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getGrant(
      _grantId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    grants(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    releaseGrant(
      _grantId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verifyAttendance(
      _grantId: PromiseOrValue<BigNumberish>,
      _zkProofHash: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
