/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChildVitaGrant } from "./ChildVitaGrant";
export * as factories from "./factories";
export { ChildVitaGrant__factory } from "./factories/ChildVitaGrant__factory";
